services:
  validation-password-api-container:
    container_name: validation-password-api-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - NODE_ENV=development
    ports:
      - "8080:8080"
